In [1]:
import numpy as np
import numpy.typing as npt

In [8]:
def unity_to_right_handed(matrix: npt.NDArray) -> npt.NDArray:
    """
    Convert a 4x4 transformation matrix from Unity's left-handed
    (Y-up) coordinate system to a right-handed system where
    Y is up, X is to the right, and Z points toward the viewer.

    Parameters
    ----------
    matrix : np.ndarray
        A 4x4 NumPy array representing the pose in Unity's coordinate system.

    Returns
    -------
    np.ndarray
        A 4x4 NumPy array representing the equivalent pose
        in the specified right-handed coordinate system.
    """
    # 1) Flip Z to convert from LH to RH
    flip_z = np.diag([1, 1, -1, 1])

    # Phone orientation fix.
    # 2) Define rotation about Z by -90 degrees
    #    In a typical right-handed system, this matrix is:
    #      [  0   1   0   0 ]
    #      [ -1   0   0   0 ]
    #      [  0   0   1   0 ]
    #      [  0   0   0   1 ]
    rz_neg_90 = np.array(
        [[0, 1, 0, 0], [-1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]], dtype=float
    )

    # 3) Combine: flip_z * M_Unity * flip_z => Right-handed
    #    Then multiply on the left by Rz(-90) to do the final rotation.
    return flip_z @ matrix @ flip_z

In [9]:
pt = np.array([[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [4.111246, 2.055851, 4.253376, 1]]).T

print(pt)
unity_to_right_handed(pt)

[[0.       0.       0.       4.111246]
 [0.       0.       0.       2.055851]
 [0.       0.       0.       4.253376]
 [0.       0.       0.       1.      ]]


array([[ 0.      ,  0.      ,  0.      ,  4.111246],
       [ 0.      ,  0.      ,  0.      ,  2.055851],
       [ 0.      ,  0.      ,  0.      , -4.253376],
       [ 0.      ,  0.      ,  0.      ,  1.      ]])